/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 pot.gltf --transform 
Files: pot.gltf [6.91KB] > C:\Users\toshi\Desktop\ThreeJs\create-a-game-with-r3f-re\pot-transformed.glb [3.39KB] (51%)
*/

import React, { useRef } from "react";
import { useGLTF, MeshTransmissionMaterial } from "@react-three/drei";

export default function Pot(props) {
  const { nodes, materials } = useGLTF("/models/utensil/pot.glb");
  return (
    <group {...props} dispose={null}>

      {/* BODY */}
      <mesh geometry={nodes.Mesh_pot.geometry}>
        <MeshTransmissionMaterial
          color="lightsteelblue"
          transmissionSampler
          transmission={1.2}
          thickness={0.3}
          backsideThickness={0.2}
          chromaticAberration={0.1}
          distortion={0.5}
          resolution={512}
        />
      </mesh>

      {/* HANDLES */}
      <mesh geometry={nodes.Mesh_pot_1.geometry}>
        <meshStandardMaterial color="#563F2E" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/utensil/pot.glb");
