/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 pot-lid.gltf --transform 
Files: pot-lid.gltf [5.73KB] > C:\Users\toshi\Desktop\ThreeJs\create-a-game-with-r3f-re\pot-lid-transformed.glb [2.97KB] (48%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function PotLid(props) {
  const { nodes, materials } = useGLTF("/models/pot-lid.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_potLid.geometry}
        material={materials.greyDark}
      />
      <mesh
        geometry={nodes.Mesh_potLid_1.geometry}
        material={materials._defaultMat}
      />
    </group>
  );
}

useGLTF.preload("/models/pot-lid.glb");
