/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 hamburger.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Hamburger(props) {
  const { nodes, materials } = useGLTF('/models/hamburger.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bottomBun.geometry} material={materials.BunMaterial} position={[0, -2.331, 0]} />
      <mesh geometry={nodes.meat.geometry} material={materials.SteakMaterial} position={[0, 0.486, 0]} />
      <mesh geometry={nodes.cheese.geometry} material={materials.CheeseMaterial} position={[0, 0.709, 0]} />
      <mesh geometry={nodes.topBun.geometry} material={materials.BunMaterial} position={[0, -0.56, 0]} />
    </group>
  )
}

useGLTF.preload('/models/hamburger.glb')
