/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bear.gltf --transform 
Files: bear.gltf [110.44KB] > C:\Users\toshi\Desktop\ThreeJs\create-a-game-with-r3f-re\bear-transformed.glb [11.01KB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bear(props) {
  const { nodes, materials } = useGLTF('/models/animals/bear.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.character_bear.geometry} material={materials['BrownDark.036']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.character_bearHead.geometry} material={materials['Black.025']} position={[0, 0.704, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/animals/bear.glb')
