/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 unicorn.gltf --transform 
Files: unicorn.gltf [35.26KB] > C:\Users\toshi\Desktop\ThreeJs\create-a-game-with-r3f-re\unicorn-transformed.glb [21.77KB] (38%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Unicorn(props) {
  const { nodes, materials } = useGLTF("/models/animals/unicorn.glb");
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Bone} />
      <primitive object={nodes.Bone037} />
      <primitive object={nodes.Bone014} />
      <primitive object={nodes.Bone035} />
      <primitive object={nodes.Bone036} />
      <primitive object={nodes.Bone038} />
      <group
        position={[0, 1.242, 0]}
        rotation={[0, Math.PI / 6, 0]}
        scale={0.489}
      >
        <skinnedMesh
          geometry={nodes.Cube.geometry}
          material={materials["Material.001"]}
          skeleton={nodes.Cube.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Cube_1.geometry}
          material={materials["Material.003"]}
          skeleton={nodes.Cube_1.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/animals/unicorn.glb");
