/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 mushroom.gltf --transform 
Files: mushroom.gltf [3.86KB] > C:\Users\toshi\Desktop\ThreeJs\create-a-game-with-r3f-re\mushroom-transformed.glb [2.26KB] (41%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Mushroom(props) {
  const { nodes, materials } = useGLTF("/models/vegetables/mushroom.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_mushroom.geometry}
        material={materials.brownDark}
      />
      <mesh
        geometry={nodes.Mesh_mushroom_1.geometry}
        material={materials.brownLight}
      />
    </group>
  );
}

useGLTF.preload("/models/vegetables/mushroom.glb");
