/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 paprika.gltf --transform 
Files: paprika.gltf [4.45KB] > C:\Users\toshi\Desktop\ThreeJs\create-a-game-with-r3f-re\paprika-transformed.glb [2.54KB] (43%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Paprika(props) {
  const { nodes, materials } = useGLTF("/models/vegetables/paprika.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_paprika.geometry} material={materials.red} />
      <mesh
        geometry={nodes.Mesh_paprika_1.geometry}
        material={materials.green}
      />
    </group>
  );
}

useGLTF.preload("/models/vegetables/paprika.glb");
