/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tomato.gltf --transform 
Files: tomato.gltf [4.38KB] > C:\Users\toshi\Desktop\ThreeJs\create-a-game-with-r3f-re\tomato-transformed.glb [2.5KB] (43%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Tomato(props) {
  const { nodes, materials } = useGLTF("/models/vegetables/tomato.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_tomato.geometry} material={materials.red} />
      <mesh
        geometry={nodes.Mesh_tomato_1.geometry}
        material={materials.green}
      />
    </group>
  );
}

useGLTF.preload("/models/vegetables/tomato.glb");
